# Generated by Django 6.0.4 on 2026-04-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='nano_coins_included',
            field=models.PositiveIntegerField(default=0, help_text='1 oyga beriladigan umumiy nano koin miqdori (haftada 1/4 beriladi)'),
        ),
    ]
