# Generated by Django 6.0.4 on 2026-04-22 00:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_tariff_nano_coins_included'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Obuna', 'verbose_name_plural': 'Obunalar'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Tarif (narxlar)', 'verbose_name_plural': 'Tariflar (narxlar)'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='generations_used',
            field=models.IntegerField(default=0, verbose_name='Ishlatilgan AI'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='projects_created',
            field=models.IntegerField(default=0, verbose_name='Yaratilgan loyihalar'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Faol'), ('EXPIRED', "Muddati o'tgan"), ('CANCELED', 'Bekor qilingan')], default='ACTIVE', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.tariff', verbose_name='Tarif'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='ai_generations_limit',
            field=models.IntegerField(default=10, verbose_name='AI generatsiya limiti'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='duration_days',
            field=models.IntegerField(default=30, verbose_name='Muddati (kun)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tarif nomi'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='nano_coins_included',
            field=models.PositiveIntegerField(default=0, help_text='1 oyga beriladigan umumiy nano koin miqdori (haftada 1/4 qismi beriladi)', verbose_name='Oyiga nano koin'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='pages_per_project_limit',
            field=models.IntegerField(default=5, verbose_name='Bir loyihada sahifalar'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi ($)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='projects_limit',
            field=models.IntegerField(default=1, verbose_name='Loyihalar soni'),
        ),
    ]
