# Generated by Django 6.0.4 on 2026-04-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0005_conversation_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_budget_nano',
            field=models.PositiveIntegerField(default=500, help_text='Chat uchun bonus nano koin (har yangi chatda 500 beriladi)'),
        ),
    ]
