# Generated by Django 6.0.4 on 2026-04-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens_balance',
            field=models.PositiveIntegerField(default=10000, help_text='Foydalanuvchining joriy token balansi', verbose_name='tokens balance'),
        ),
    ]
